language: python
python:
- '2.7'
before_install:
- sudo apt-get update -qq
- sudo apt-get install gcc libffi-dev libldap2-dev libsasl2-dev libssl-dev python-dev
install:
- python setup.py install
script:
- python setup.py test
deploy:
  provider: pypi
  user: opennode
  password:
    secure: ZvBuYUxGh6vPsIYHgyH9K+7A4IJyR2dFYt0cWZp24mR4+XkCmd0DBtEGyrNyEzN+z5v8BU4OKyAwIUPVt54fHLBsBMbvgXVgn3DKNF5LkCQ7A8/GFeD9WpUk0TYdFkab6di+UhBCsIZN43ls8yybuWYDjEVqUZSRNRVBCOZDY6/1TWVgYbDg4KjtclgBwDSBeBJPO2w5VUPFo3KGqRph/VfGABaALuBsz4TdPUr11QmcXkFhfW8iWeBm6A+3DcdS0JoAMYfBfi+XXUMciYm5hV4Ws5pSOBXWaRAoheczLf3p+APmODBEjzp7ZT89U0crpWVmqDTp/wcjRxHZUAM6qAvac6YVvWcU7y+JBvB2TIAEjHwgwq5CyPpcH7/Xp4LPePp8D3/7VYSJazPdVwxJjflovu1aPdsx1Kz68P1UXwH4yApZ6b0ncSxXFN0KUovkUMyGHGUZU22/u4pDvCOThG6bdOpOuh/EtYbA3wogecUCTc/k6h1Wq+f5K39dRMSQUeeUH4NxtnjiJDvo86eYBewdqS0C5uehsE9hdy1eZq6oG8n2LSTld85cNyuWJbv1YChAzGa4nilUlRzsWfNduOO3OuTG5ibrrPuo8uxdyFfmc0xAGEKiu35QEp7AyH739h4K9yb0uwP68+YnfooXh2MEYsyxeRRUj1hV6dUCP1w=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: opennode/waldur-auth-valimo
